### ISSUE TITLE
28. Thống kê đơn hàng

### ISSUE THREAD

**Issue by ChiCuong002** [ChiCuong002/BanDienThoaiDiDong#12]
- Giao diện: Danh sách đơn đặt hàng, được hiển thị theo dạng table gồm các thông tin (địa chỉ, ngày đặt hàng, trạng thái giao hàng, trạng thái thanh toán, giá trị đơn hàng, Action), phía bên phải ngoài cùng có 1 button Action để chuyển đến trang chi tiết đơn hàng, phía trên table danh sách đơn hàng có chức năng tìm kiếm dạng sort theo trạng thái đơn hàng.

- Xử lí: Đọc dữ liệu từ bảng HDBAN.
Sử dụng vòng lặp foreach để hiển thị thông tin đơn hàng lên View.
- Lưu trữ: không có

**Comment by Windyyyyyyyyy** [comment]
Đã nhận

**Comment by Windyyyyyyyyy** [comment]
Đã hoàn thành
