### ISSUE TITLE
29. Xem chi tiết đơn hàng đã đặt mua

### ISSUE THREAD

**Issue by ChiCuong002** [ChiCuong002/BanDienThoaiDiDong#13]
. Giao diện: giao diện chi tiết đơn hàng của khách hàng bao gồm các thông tin (Hình sản phẩm, tên sản phẩm, màu sác sản phẩm, dung lượng, số lượng và đơn giá), phía trên các sản phẩm khách hàng đã đặt sẽ có 1 dòng cảm ơn khách hàng, phía dưới là thông tin đơn hàng bao gồm các thông tin (Mã hóa đơn, trạng thái đơn hàng, trạng thái thanh toán), và phía dưới cùng của giao diện hiển thị tổng giá trị đơn hàng của khách hàng.
. Xử lí: load thông tin các sản phẩm khách hàng đặt mua bao gồm hình sản phẩm, tên sản phẩm, màu sắc sản phẩm, dung lượng, số lượng, giá, load thông tin đơn hàng bao gồm mã đơn hàng, trạng thái đơn hàng và trạng thái thanh toán, load tổng trị giá đơn hàng
. Lưu trữ: không có

**Comment by lamtrungnghia1202** [comment]
Đã nhận

**Comment by lamtrungnghia1202** [comment]
Đã hoàn thành
