### ISSUE TITLE
30. Xem danh sách khách hàng

### ISSUE THREAD

**Issue by ChiCuong002** [ChiCuong002/BanDienThoaiDiDong#14]
- Giao diện: 

Một list thông tin khác hàng sẽ hiện ra bên cột bên phải của trang gồm các thông tin cơ bản của khách hàng như tên khách hàng, số điện thoại, địa chỉ, ngày sinh

- Xử lý: 

Đọc dữ liệu trong bảng KHACHHANG

- Lưu trữ: 

Không lưu trữ

**Comment by admd1142** [comment]
đã nhận

**Comment by obito0147** [comment]
da hoan thanh
