### ISSUE TITLE
17. Sắp xếp sản phẩm

### ISSUE THREAD

**Issue by lamtrungnghia1202** [ChiCuong002/BanDienThoaiDiDong#26]
- Giao diện: Ở giao diện danh sách sản phẩm phía dưới slider bên tay phải có button sort theo tên sản phẩm
- Xử lý: load dữ liệu theo từ khóa đã nhập, sắp xếp sản phẩm theo mục đã chọn
- Lưu trữ: Không có

**Comment by obito0147** [comment]
đã nhận

**Comment by obito0147** [comment]
đã hoàn thành
