### ISSUE TITLE
Hủy đơn hàng

### ISSUE THREAD

**Issue by obito0147** [ChiCuong002/BanDienThoaiDiDong#46]
. Giao diện: kế bên mỗi đơn hàng có một button "Hủy", khi click vào button sẽ chuyển tới trang xác nhận hủy đơn hàng bao gồm các thông tin(họ tên khách hàng, ngày đặt hàng, địa chỉ giao hàng, trạng thái đơn hàng), bên dưới phần thông tin có 1 button "Xóa" để submit.
. Xử lí: khi click button "Xóa", đơn hàng sẽ được xóa khỏi danh sách dựa vào index.
. Lưu trữ: xóa đơn hàng trên CSDL.

**Comment by lamtrungnghia1202** [comment]
Đã nhận

**Comment by lamtrungnghia1202** [comment]
Đã hoàn thành

**Comment by lamtrungnghia1202** [comment]
Đã hoàn thành
