### ISSUE TITLE
Đăng xuất

### ISSUE THREAD

**Issue by lamtrungnghia1202** [ChiCuong002/BanDienThoaiDiDong#47]
Giao diện:
-Được hiển thị bên trang chủ, nằm trong thẻ anchor và được chứa trong một dropdown list của mục hiển thị tên khách hàng

Xử lí:
-Khi ấn Đăng xuất thì sẽ quay về trang Đăng nhập, đồng thời data(Email, mật khẩu) được lưu trong session sẽ bị mất

Lưu trữ: Không có

**Comment by Windyyyyyyyyy** [comment]
Đã hoàn thành
