### ISSUE TITLE
Sắp xếp, tìm kiếm sản phẩm

### ISSUE THREAD

**Issue by lamtrungnghia1202** [ChiCuong002/BanDienThoaiDiDong#48]
- Giao diện: về tìm kiếm ở trang chủ và trang danh sách sản phẩm theo hãng sẽ có 1 thanh tìm kiếm phía dưới slider để nhập liệu và 1 nút button để submit. về sắp xếp ở giao diện danh sách sản phẩm phía dưới slider bên tay phải có một select option có thể chọn sắp xếp theo giá và tên.
- Xử lý: về tìm kiếm Load dữ liệu sản phẩm theo từ khóa nhập vào từ View hiển thị lên giao diện. về sắp xếp load dữ liệu từ select option khi chọn thông qua viewbag
- Lưu trữ: không có

**Comment by obito0147** [comment]
đã nhận

**Comment by obito0147** [comment]
đã hoàn thành
