### ISSUE TITLE
Xóa sản phẩm

### ISSUE THREAD

**Issue by lamtrungnghia1202** [ChiCuong002/BanDienThoaiDiDong#50]
Giao diện: Tại mục sửa thông tin sản phẩm sẽ hiển thị ra các thông tin như tên sản phẩm, mô tả, dung lượng, mã màu, dòng máy, mã loại, số lượng và hình ảnh của sản phẩm phía bên tay phải và phía dưới cùng có button cập nhật.

Xử lý: khi chọn button Sửa, một form điền theo mẫu sẽ xuất hiện, bạn có thể sữa các thông tin đã hiển thị ở phần giao diện được nêu ở trên, sau đó ấn vào nút lưu thì thông tin sẽ được cập nhật!

Lưu trữ: điều chỉnh lại thông tin của sản phẩm sau đó update trên CSDL

**Comment by admd1142** [comment]
đã nhận!
