### ISSUE TITLE
Xem chi tiết sản phẩm (Admin)

### ISSUE THREAD

**Issue by Windyyyyyyyyy** [ChiCuong002/BanDienThoaiDiDong#51]
-Giao diện: một form sẽ hiện ra gồm các thông tin cơ bản của sản phẩm như: Tên sản phẩm, mô tả ngắn về sản phẩm, dung lượng, mã màu , dòng máy, mã loại được sắp xếp theo dạng cột thẳng, và hình ảnh của sản phẩm được hiển thị phía bên phải

-Xử lí: click vào button Chi tiết nằm ở cuối ở danh sách của mỗi sản phẩm thì form chi tiết sản phẩm sẽ được hiển thị. Dữ liệu hiển thị được lấy từ database bảng SẢN PHẨM.

-Lưu trữ: Không có

**Comment by admd1142** [comment]
đã nhận!

**Comment by admd1142** [comment]
đã hoàn thành
