### ISSUE TITLE
6. Xem chi tiết sản phẩm (Khách hàng)

### ISSUE THREAD

**Issue by Windyyyyyyyyy** [ChiCuong002/BanDienThoaiDiDong#53]
-Giao diện: khi click vào một sản phẩm bất kỳ sẽ hiển thị thông tin chi tiết của sản phẩm. Phía bên trái sẽ là hình ảnh sản phẩm, phía bên phải sẽ hiển thị tên sản phẩm, giá sản phẩm, mô tả sản phẩm và phía dưới là button thêm vào giỏ hàng.
Ngoài ra còn có mục chọn lựa màu sắc và dung lượng tương ứng với dòng máy.
-Xử lý: 
Đọc dữ liệu từ bảng SANPHAM để lấy thông tin sản phẩm như: tên sản phẩm, mô tả, giá thành và mã sản phẩm.
Dựa theo mã sản phẩm đọc dữ liệu từ bảng: Color, Capacity, Seri để lấy ra danh sách các màu, danh sách các dung lượng hiện có của sản phẩm.
Hiển thị thông qua ViewBag và View-Model
-Lưu trữ: Không có

**Comment by ChiCuong002** [comment]
đã nhận

**Comment by ChiCuong002** [comment]
đã hoàn thành
