### ISSUE TITLE
Xóa khách hàng

### ISSUE THREAD

**Issue by Windyyyyyyyyy** [ChiCuong002/BanDienThoaiDiDong#56]
-Giao diện: ở giao diện danh sách khách hàng thì danh sách được hiển thị dưới dạng là table bao gồm STT, họ tên khách hàng, email, địa chỉ, sđt, mật khẩu, hiển thị và cuối mỗi dòng khách hàng sẽ có 1 button là xóa  
-Xử lí: chọn vào button xóa sẽ hiển thị giao diện edit sau đó chọn hiện thị của khách hàng là false sẽ ẩn đi khách hàng 
-Lưu trữ: cập nhật lại hiện thị của khách hàng và lưu xuống csdl

**Comment by obito0147** [comment]
đã nhận

**Comment by obito0147** [comment]
đã hoàn thành
