### ISSUE TITLE
29. Xóa sản phẩm khỏi giỏ hàng

### ISSUE THREAD

**Issue by Windyyyyyyyyy** [ChiCuong002/BanDienThoaiDiDong#57]
Giao diện: 
-	Hiển thị theo 1 cột với width:70%, display ở giữa màn hình.
-	Mỗi row là 1 div hiển thị thông tin của một sản phẩm trong giỏ hàng:
•	Mỗi row có 3 cột: cột đầu tiên hiển thị hình ảnh sản phẩm, bên dưới ảnh có button “Xóa” để xóa sản phẩm khỏi giỏ hàng. Cột thứ hai hiển thị thông tin của sản phẩm. Cột thứ ba hiển thị giá thành của sản phẩm.
•	Và 1 thẻ <div></div> chứa 1 thanh input và một button “-“ bên trái thanh input, một button “+” bên phải thanh input. Để cập nhật số lượng sản phẩm. display bên phải div.
-	Và mục chọn hình thức thanh toán trực tiếp hoặc thanh toán trực tuyến.
-	Row cuối chứa tổng giá trị đơn hàng và một button “TIẾP THEO”. Để thới trang nhập thông tin giao hàng và thanh toán
Xử lí:
- Khi click button xóa thực hiện gọi action xóa sản phẩm ở controller, truyền mã sản phẩm và mã giỏ hàng đến controller
- Thực thi remove sản phẩm  có mã sản phẩm và mã giỏ hàng phù hợp ở bảng ChiTietGH.
-Lưu trữ
- Lưu lại bảng ChiTietGH sau khi xóa sản phẩm khỏi giỏ hàng

**Comment by ChiCuong002** [comment]
đã nhận

**Comment by ChiCuong002** [comment]
đã hoàn thành
