### ISSUE TITLE
27. Xem danh sách khách hàng

### ISSUE THREAD

**Issue by Windyyyyyyyyy** [ChiCuong002/BanDienThoaiDiDong#58]
Giao diện:
Danh sách khách hàng được hiển thị dưới dạng table bao gồm các trường họ tên khách hàng, email, địa chỉ, sđt, mật khẩu ở dạng đã mã hóa và tình trạng hiển thị phía trên table có một thanh search để tìm kiếm khách hàng theo số điện thoại

Xử lý:
Đọc dữ liệu trong bảng KHACHHANG

Lưu trữ:
Không lưu trữ

**Comment by admd1142** [comment]
đã nhận!
