### ISSUE TITLE
10. Chuyển trạng thái đơn hàng

### ISSUE THREAD

**Issue by admd1142** [ChiCuong002/BanDienThoaiDiDong#60]
. Giao diện: kế bên mỗi đơn hàng có một button "Cập nhật",  giao diện chuyển trạng thái đơn hàng hiển thị các thông tin bao gồm mã đơn hàng, mã khách hàng, ngày đặt hàng, địa chỉ giao hàng, tổng tiền và trạng thái đơn hàng được hiển thị dưới dạng dropdown để có thể cập nhật trạng thái của đơn hàng.
. Xử lí: khi click vào button "Lưu", đơn hàng sẽ được cập nhật trạng thái dựa vào Index.
. Lưu trữ: Cập nhật thuộc tính trạng thái đơn hàng ở bảng HDBAN.

**Comment by lamtrungnghia1202** [comment]
Đã nhận

**Comment by lamtrungnghia1202** [comment]
Đã hoàn thành
