### ISSUE TITLE
3.Thêm sản phẩm và giỏ hàng

### ISSUE THREAD

**Issue by admd1142** [ChiCuong002/BanDienThoaiDiDong#61]
Giao diện:
Trang chi tiết sản phẩm có được chia thành 2 column chính. Column bên trái hiển thị hình ảnh sản phẩm. Bên dưới hình ảnh là
chứa thông tin giao hàng.
Column phải hiên thị thông tin của sản phẩm lần lượt là:
Thẻ h3. Hiển thị tên sản phẩm.
Thẻ h4. Hiển thị giá tiền sản phẩm, theo định dạng 1,000,000.
Thẻ p. Hiển thị mô tả của sản phẩm.
Dùng vòng lặp for để hiển thị màu sắc của dòng sản phẩm.
Dùng vòng lặp for để hiển thị dung lượng của dòng sản phẩm.
Button “Thêm vào giỏ hàng” ngay sau thông tin sản phẩm.
Xử lý:
Khi click button “Thêm vào giỏ hàng”. Truyền mã sản phẩm vào action AddToCart.
Kiểm tra khách hàng đã đăng nhập hay chưa. Nếu chưa đăng nhập thì dẫn đến trang đăng nhập.
Ngược lại thực hiện lưu thông tin sản phẩm bao gồm: MaSP, MaGH, SoLuong vào bảng ChiTietGH.
Kiểm tra nếu như trong bảng ChiTietGH, nếu đã tồn tại 1 MaSP và MaGH tương ứng thì tăng số lượng sản phẩm lên thêm 1. Ngược lại thêm add ChiTietGH mới.
Sau đó nếu thành công hiển thị đến trang "Giỏ hàng"
Lưu trữ:
Lưu trữ MaSP, MaGH, SoLuong vào bảng ChiTietGH với MaGH tương ứng với người dùng đang đăng nhập.

**Comment by ChiCuong002** [comment]
đã nhận

**Comment by ChiCuong002** [comment]
đã hoàn thành
