### ISSUE TITLE
Layout quản trị (Cường)

### ISSUE THREAD

**Issue by admd1142** [ChiCuong002/BanDienThoaiDiDong#62]
Giao diện:

- Layout quản trị viên được thiết kế với sidebar ở bên trái chứa các thẻ <a> dẫn đến các chức năng quản lý.
- Và một thanh navbar ở trên để hiển thị thông tin người quản trị đang đăng nhập.
- Phần main sẽ chửa RenderBody() để render các view phù hợp với tùng action.

Xử lý:
Không có
Lưu trữ:
Không có

**Comment by ChiCuong002** [comment]
đã nhận

**Comment by ChiCuong002** [comment]
đã hoàn thành
