### ISSUE TITLE
5.Layout trang chủ

### ISSUE THREAD

**Issue by admd1142** [ChiCuong002/BanDienThoaiDiDong#63]
-Giao diện: gồm phần header là thanh navbar và footer là thông tin của cửa hàng. Trên thanh navbar có các mục hiển thị từ trái qua là tên cửa hàng, button Trang Chủ, button Sản Phẩm, button đăng ký và button đăng nhập. Còn phần footer được nhập dữ liệu cứng
-Xử lý: khi chọn vào Trang chủ sẽ hiển thị trang chủ, khi chọn sản phẩm sẽ hiển thị mục danh sách sản phẩm, chọn mục đăng nhập sẽ hiển thị phần đăng nhập cho khách hàng và đăng ký cho khách hàng
-Lưu trữ: Không có

**Comment by obito0147** [comment]
đã nhận

**Comment by obito0147** [comment]
đã hoàn thành
