### ISSUE TITLE
Cập nhật thông tin cá nhân

### ISSUE THREAD

**Issue by admd1142** [ChiCuong002/BanDienThoaiDiDong#64]
- Giao diện: giao diện bao gồm 1 title thể hiện chủ đề của giao diện và gồm các trường như HoTen, Email, DiaChi,SoDienThoai,UserName,MatKhau và cuối cùng là button save khi đã chỉnh sửa thông tin
- Xử lý: gồm các input để nhập dữ liệu chỉnh sửa thông tin theo các trường, và button save để lưu thông tin sau chỉnh sửa
- Lưu trữ: lưu thông tin chỉnh sửa xuống csdl và cập nhật lại csdl

**Comment by obito0147** [comment]
đã nhận

**Comment by obito0147** [comment]
đã hoàn thành
