### ISSUE TITLE
Cấp tài khoản cho nhân viên

### ISSUE THREAD

**Issue by admd1142** [ChiCuong002/BanDienThoaiDiDong#66]
-Giao diện: 
        + Được phủ trong một Layout chung của Admin 
        + Một form import file gồm label + input, button Import được sắp xếp theo dạng flex-direction: column và được căn bởi các thuộc tính display: flex, justify-content, align-items
        + Một table danh sách nhân viên với các trường ứng với Model NhanVien (MaNV, HoTen, Email, DiaChi, SoDienThoai, UserName, MatKhau)

-Xử lí:
        + Sử dụng thư viện OpenXML để có thể lấy dữ liệu từ Excel 
        + Khi ấn nút Import file
                1. Sẽ báo lỗi nếu file không phải định dạng .xlsx
                2. Sẽ báo lỗi khi gặp sự gián đoạn trong lúc lấy dữ liệu
                3. Sẽ báo thành công khi lấy dữ liệu và hiển thị thành công. Mỗi lần lấy dữ liệu sẽ xóa hết tất cả dữ liệu trc đó và import lại từ đầu.
             
-Lưu trữ: Lưu xuống bảng NhanVien trong database ứng với các trường được truyền vào Model NhanVien khi import dữ liệu (MaNV, HoTen, Email, DiaChi, SoDienThoai, UserName, MatKhau)

**Comment by Windyyyyyyyyy** [comment]
Đã nhận

**Comment by Windyyyyyyyyy** [comment]
Đã hoàn thành
