### ISSUE TITLE
Sắp xếp đơn hàng

### ISSUE THREAD

**Issue by admd1142** [ChiCuong002/BanDienThoaiDiDong#67]
. Giao diện: ở trang danh sách đơn đặt hàng, có chức năng sắp xếp theo dạng sort, được sort theo trạng thái đơn hàng để tìm kiếm đơn hàng.
. Xử lí: load dữ liệu đơn hàng theo trạng thái đơn hàng để hiển thị lên giao diện.
. Lưu trữ: không có.

**Comment by lamtrungnghia1202** [comment]
Đã nhận

**Comment by lamtrungnghia1202** [comment]
Đã hoàn thành
